=== dougthor42/nuget-api-v3-jsonschemas/schemas/NuGet.Api.v3.RegistrationsBaseUrl.Page.json
{
    "$schema": "http://json-schema.org/schema#",
    "id": "NuGet.Api.v3.RegistrationsBaseUrl.Page.json",

    "definitions": {
        "str_or_array_of_str": {
            "anyOf": [
                { "type": "string" },
                { "type": "array", "items": { "type": "string" } }
            ]
        },

        "version_range": {
        },

        "dependency": {
            "type": "object",
            "properties": {
                "id": { "type": "string" },
                "range": { "$ref": "#/definitions/version_range" },
                "registration": { "type": "string" }
            },
            "required": [ "id" ]
        },

        "dependency_group": {
            "type": "object",
            "properties": {
                "targetFramework": { "type": "string" },
                "dependencies": {
                    "type": "array",
                    "items": { "$ref": "#/definitions/dependency" }
                }
            }
        },

        "catalog_entry": {
            "type": "object",
            "properties": {
                "@id": { "type": "string" },
                "authors": { "$ref": "#/definitions/str_or_array_of_str" },
                "dependencyGroups": {
                    "type": "array",
                    "items": { "$ref": "#/definitions/dependency_group" }
                },
                "description": { "type": "string" },
                "iconUrl": { "type": "string" },
                "id": { "type": "string" },
                "licenseUrl": { "type": "string" },
                "listed": { "type": "boolean" },
                "minClientVersion": { "type": "string" },
                "projectUrl": { "type": "string" },
                "published": { "type": "string" },
                "reqireLicenseAcceptance": { "type": "boolean" },
                "summary": { "type": "string" },
                "tags": { "$ref": "#/definitions/str_or_array_of_str" },
                "title": { "type": "string" },
                "version": { "type": "string" }
            },
            "required": [ "@id", "id", "version" ]
        },

        "registration_leaf": {
            "type": "object",
            "properties": {
                "@id": { "type": "string" },
                "catalogEntry": { "$ref": "#/definitions/catalog_entry" },
                "packageContent": { "type": "string" }
            },
            "required": [ "@id", "catalogEntry", "packageContent" ]
        }
    },

    "type": "object",
    "properties": {
        "@id": { "type": "string" },
        "count": { "type": "integer" },
        "items": {
            "type": "array",
            "items": { "$ref": "#/definitions/registration_leaf" }
        },
        "lower": { "type": "string" },
        "parent": { "type": "string" },
        "upper": { "type": "string" }
    },
    "required": [ "count", "items", "lower", "parent", "upper" ]
}

=== dougthor42/nuget-api-v3-jsonschemas/samples/RegistrationsBaseUrl.Page.json
{
  "count": 2,
  "lower": "1.0.531",
  "parent": "https://api.nuget.org/v3/registration3/ravendb.client/index.json",
  "upper": "1.0.729-unstable",
  "items": [
    {
      "@id": "https://api.nuget.org/v3/registration3/ravendb.client/1.0.531.json",
      "@type": "Package",
      "commitId": "e0b9ca79-75b5-414f-9e3e-de9534b5cfd1",
      "commitTimeStamp": "2017-10-26T14:12:19.3439088Z",
      "catalogEntry": {
        "@id": "https://api.nuget.org/v3/catalog0/data/2015.02.01.11.38.37/ravendb.client.1.0.531.json",
        "@type": "PackageDetails",
        "authors": "Hibernating Rhinos",
        "iconUrl": "http://static.ravendb.net/logo-for-nuget.png",
        "id": "RavenDB.Client",
        "licenseUrl": "http://www.ravendb.net/licensing",
        "listed": false,
        "packageContent": "https://api.nuget.org/v3-flatcontainer/ravendb.client/1.0.531/ravendb.client.1.0.531.nupkg",
        "projectUrl": "http://www.ravendb.net/",
        "published": "1900-01-01T00:00:00+00:00",
        "requireLicenseAcceptance": true,
        "title": "RavenDB (Client Only)",
        "version": "1.0.531"
      },
      "packageContent": "https://api.nuget.org/v3-flatcontainer/ravendb.client/1.0.531/ravendb.client.1.0.531.nupkg",
      "registration": "https://api.nuget.org/v3/registration3/ravendb.client/index.json"
    },
    {
      "@id": "https://api.nuget.org/v3/registration3/ravendb.client/1.0.729-unstable.json",
      "@type": "Package",
      "commitId": "e0b9ca79-75b5-414f-9e3e-de9534b5cfd1",
      "commitTimeStamp": "2017-10-26T14:12:19.3439088Z",
      "catalogEntry": {
        "@id": "https://api.nuget.org/v3/catalog0/data/2015.02.01.18.22.05/ravendb.client.1.0.729-unstable.json",
        "@type": "PackageDetails",
        "authors": "Hibernating Rhinos",
        "iconUrl": "http://static.ravendb.net/logo-for-nuget.png",
        "id": "RavenDB.Client",
        "licenseUrl": "http://www.ravendb.net/licensing",
        "listed": false,
        "packageContent": "https://api.nuget.org/v3-flatcontainer/ravendb.client/1.0.729-unstable/ravendb.client.1.0.729-unstable.nupkg",
        "projectUrl": "http://www.ravendb.net/",
        "published": "1900-01-01T00:00:00+00:00",
        "requireLicenseAcceptance": true,
        "summary": "This package includes the clinet API of RavenDB.",
        "title": "RavenDB Client",
        "version": "1.0.729-Unstable"
      },
      "packageContent": "https://api.nuget.org/v3-flatcontainer/ravendb.client/1.0.729-unstable/ravendb.client.1.0.729-unstable.nupkg",
      "registration": "https://api.nuget.org/v3/registration3/ravendb.client/index.json"
    }
  ]
}
